using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TodoApp.Domain.Todos;

namespace TodoApp.Infrastructure.Persistence.Configurations;

/// <summary>
/// Maps <see cref="PersonalTodoComment"/> to the "PersonalTodoComments" table. The relationship
/// back to the owning <see cref="PersonalTodo"/> (including cascade delete) is configured on
/// <see cref="PersonalTodoConfiguration"/> via the "_comments" navigation.
/// </summary>
internal sealed class PersonalTodoCommentConfiguration
    : IEntityTypeConfiguration<PersonalTodoComment>
{
    /// <summary>Configures table mapping, keys, and the UTC-ticks timestamp conversion.</summary>
    public void Configure(EntityTypeBuilder<PersonalTodoComment> builder)
    {
        builder.ToTable("PersonalTodoComments");
        builder.HasKey(comment => comment.Id);
        // Ids are assigned by the domain, not generated by the database.
        builder.Property(comment => comment.Id)
            .ValueGeneratedNever();
        builder.Property(comment => comment.TodoId).IsRequired();
        builder.Property(comment => comment.Body)
            .HasMaxLength(2000)
            .IsRequired();
        // Store DateTimeOffset as raw UTC ticks (long) for portability across SQLite/Postgres,
        // rather than relying on each provider's native DateTimeOffset support.
        builder.Property(comment => comment.CreatedAt)
            .HasConversion(
                value => value.UtcTicks,
                value => new DateTimeOffset(value, TimeSpan.Zero))
            .IsRequired();
        // Supports fetching a todo's comments in chronological order.
        builder.HasIndex(comment => new { comment.TodoId, comment.CreatedAt });
    }
}
