using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TodoApp.Domain.Projects;

namespace TodoApp.Infrastructure.Persistence.Configurations;

/// <summary>
/// Maps <see cref="ProjectCategory"/> to the "ProjectCategories" table. Category ids are
/// generated by the domain rather than the database, and category names are unique per
/// project (enforced via a composite unique index on ProjectId + Name).
/// </summary>
internal sealed class ProjectCategoryConfiguration
    : IEntityTypeConfiguration<ProjectCategory>
{
    /// <summary>Configures table mapping, keys, and the per-project unique name constraint.</summary>
    public void Configure(EntityTypeBuilder<ProjectCategory> builder)
    {
        builder.ToTable("ProjectCategories");
        builder.HasKey(category => category.Id);
        // Ids are assigned by the domain (e.g. Guid.NewGuid() in the entity), not by the store.
        builder.Property(category => category.Id)
            .ValueGeneratedNever();
        builder.Property(category => category.ProjectId).IsRequired();
        builder.Property(category => category.Name)
            .HasMaxLength(80)
            .IsRequired();
        // Category names only need to be unique within a project, not globally.
        builder.HasIndex(category => new { category.ProjectId, category.Name })
            .IsUnique();
    }
}
