using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TodoApp.Domain.Projects;

namespace TodoApp.Infrastructure.Persistence.Configurations;

/// <summary>
/// Maps <see cref="Sprint"/> to the "Sprints" table. The relationship back to the owning
/// <see cref="Project"/> (including cascade delete) is configured on the
/// <see cref="ProjectConfiguration"/> side via the "_sprints" navigation. Indexes support the
/// common query patterns of filtering a project's sprints by status or ordering by start date.
/// </summary>
internal sealed class SprintConfiguration : IEntityTypeConfiguration<Sprint>
{
    /// <summary>Configures table mapping, keys, the status enum conversion, and lookup indexes.</summary>
    public void Configure(EntityTypeBuilder<Sprint> builder)
    {
        builder.ToTable("Sprints");
        builder.HasKey(sprint => sprint.Id);
        // Ids are assigned by the domain, not generated by the database.
        builder.Property(sprint => sprint.Id)
            .ValueGeneratedNever();
        builder.Property(sprint => sprint.ProjectId).IsRequired();
        builder.Property(sprint => sprint.Name)
            .HasMaxLength(160)
            .IsRequired();
        builder.Property(sprint => sprint.Goal)
            .HasMaxLength(1000);
        builder.Property(sprint => sprint.StartDate).IsRequired();
        builder.Property(sprint => sprint.EndDate).IsRequired();
        // Store the enum as its underlying int rather than a string for compactness/stability.
        builder.Property(sprint => sprint.Status)
            .HasConversion<int>()
            .IsRequired();
        builder.Property(sprint => sprint.ClosedAt);
        builder.HasIndex(sprint => new { sprint.ProjectId, sprint.Status });
        builder.HasIndex(sprint => new { sprint.ProjectId, sprint.StartDate });
    }
}
