using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TodoApp.Domain.Tasks;

namespace TodoApp.Infrastructure.Persistence.Configurations;

/// <summary>
/// Maps <see cref="TaskNote"/> to the "TaskNotes" table. The relationship back to the owning
/// <see cref="TaskItem"/> (including cascade delete) is configured on the
/// <see cref="TaskItemConfiguration"/> side via the "_notes" navigation.
/// </summary>
internal sealed class TaskNoteConfiguration : IEntityTypeConfiguration<TaskNote>
{
    /// <summary>Configures table mapping, keys, and the UTC-ticks timestamp conversion.</summary>
    public void Configure(EntityTypeBuilder<TaskNote> builder)
    {
        builder.ToTable("TaskNotes");
        builder.HasKey(note => note.Id);
        // Ids are assigned by the domain, not generated by the database.
        builder.Property(note => note.Id)
            .ValueGeneratedNever();
        builder.Property(note => note.TaskId).IsRequired();
        builder.Property(note => note.AuthorId).IsRequired();
        builder.Property(note => note.Body)
            .HasMaxLength(4000)
            .IsRequired();
        // Store DateTimeOffset as raw UTC ticks (long) for portability across SQLite/Postgres,
        // rather than relying on each provider's native DateTimeOffset support.
        builder.Property(note => note.CreatedAt)
            .HasConversion(
                value => value.UtcTicks,
                value => new DateTimeOffset(value, TimeSpan.Zero))
            .IsRequired();
        // Supports fetching a task's notes in chronological order.
        builder.HasIndex(note => new { note.TaskId, note.CreatedAt });
    }
}
