using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TodoApp.Domain.Collaboration;

namespace TodoApp.Infrastructure.Persistence.Configurations;

/// <summary>
/// Maps <see cref="WorkspaceInvitation"/> to the "WorkspaceInvitations" table. Invitations are
/// deleted when their workspace is deleted, but the inviting user cannot be deleted while
/// invitations reference them (restrict), preserving audit history. The invitation token is
/// unique so it can safely be used to look up and accept/decline an invitation.
/// </summary>
internal sealed class WorkspaceInvitationConfiguration
    : IEntityTypeConfiguration<WorkspaceInvitation>
{
    /// <summary>Configures table mapping, enum conversions, uniqueness of the invite token, and relationships.</summary>
    public void Configure(EntityTypeBuilder<WorkspaceInvitation> builder)
    {
        builder.ToTable("WorkspaceInvitations");
        builder.HasKey(invitation => invitation.Id);
        // Ids are assigned by the domain, not generated by the database.
        builder.Property(invitation => invitation.Id)
            .ValueGeneratedNever();
        builder.Property(invitation => invitation.WorkspaceId)
            .IsRequired();
        builder.Property(invitation => invitation.FullName)
            .HasMaxLength(160)
            .IsRequired();
        builder.Property(invitation => invitation.Email)
            .HasMaxLength(320)
            .IsRequired();
        // Store enums as their underlying int rather than a string for compactness/stability.
        builder.Property(invitation => invitation.Role)
            .HasConversion<int>()
            .IsRequired();
        builder.Property(invitation => invitation.InvitedByUserId)
            .IsRequired();
        builder.Property(invitation => invitation.Token)
            .HasMaxLength(120)
            .IsRequired();
        builder.Property(invitation => invitation.Status)
            .HasConversion<int>()
            .IsRequired();
        builder.Property(invitation => invitation.CreatedAt)
            .IsRequired();
        builder.Property(invitation => invitation.ExpiresAt)
            .IsRequired();
        builder.Property(invitation => invitation.RespondedAt);
        // The token is what an invitee uses to accept an invite, so it must be globally unique.
        builder.HasIndex(invitation => invitation.Token)
            .IsUnique();
        // Supports checking for an existing pending invite for a given email in a workspace.
        builder.HasIndex(invitation => new
        {
            invitation.WorkspaceId,
            invitation.Email,
            invitation.Status
        });
        // Invitations belong to a workspace's lifecycle: deleting the workspace removes its invites.
        builder.HasOne<Workspace>()
            .WithMany()
            .HasForeignKey(invitation => invitation.WorkspaceId)
            .OnDelete(DeleteBehavior.Cascade);
        // Restrict rather than cascade: don't allow deleting a user who has sent invitations,
        // to keep the invitation's audit trail intact.
        builder.HasOne<UserProfile>()
            .WithMany()
            .HasForeignKey(invitation => invitation.InvitedByUserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
