using TodoApp.Domain.Common;

namespace TodoApp.Domain.Todos;

/// <summary>
/// Aggregate root for a single user's personal to-do item scoped to a specific date.
/// Owns its comments, tracks whether it was carried over from an earlier date it
/// wasn't completed on, and may optionally have been auto-generated from a
/// <see cref="DailyRoutine"/>.
/// </summary>
public sealed class PersonalTodo
{
    private readonly List<PersonalTodoComment> _comments = [];

    private PersonalTodo(
        Guid id,
        Guid userId,
        string title,
        DateOnly todoDate,
        string? notes,
        TodoPriority priority,
        Guid? dailyRoutineId,
        DateTimeOffset createdAt)
    {
        if (id == Guid.Empty)
        {
            throw new DomainValidationException(
                "Todo identifier is required.");
        }

        if (userId == Guid.Empty)
        {
            throw new DomainValidationException(
                "Todo owner is required.");
        }

        Id = id;
        UserId = userId;
        Title = NormalizeTitle(title);
        TodoDate = todoDate;
        OriginalTodoDate = todoDate;
        Notes = NormalizeNotes(notes);
        Priority = priority;
        DailyRoutineId = dailyRoutineId;
        CreatedAt = createdAt;
        UpdatedAt = createdAt;
    }

    public Guid Id { get; }

    public Guid UserId { get; }

    public string Title { get; private set; }

    public DateOnly TodoDate { get; private set; }

    public DateOnly OriginalTodoDate { get; private set; }

    public DateOnly? CarriedOverFromDate { get; private set; }

    public bool IsCarriedOver => CarriedOverFromDate.HasValue;

    public string? Notes { get; private set; }

    public TodoPriority Priority { get; private set; }

    public Guid? DailyRoutineId { get; private set; }

    public bool IsGeneratedFromDailyRoutine => DailyRoutineId.HasValue;

    public bool IsCompleted { get; private set; }

    public DateTimeOffset CreatedAt { get; }

    public DateTimeOffset UpdatedAt { get; private set; }

    public DateTimeOffset? CompletedAt { get; private set; }

    public IReadOnlyCollection<PersonalTodoComment> Comments =>
        _comments.AsReadOnly();

    /// <summary>Creates a new todo with default (Medium) priority and no daily-routine origin.</summary>
    public static PersonalTodo Create(
        Guid id,
        Guid userId,
        string title,
        DateOnly todoDate,
        string? notes,
        DateTimeOffset createdAt) =>
        new(
            id,
            userId,
            title,
            todoDate,
            notes,
            TodoPriority.Medium,
            null,
            createdAt);

    /// <summary>Creates a new todo with an explicit priority and no daily-routine origin.</summary>
    public static PersonalTodo Create(
        Guid id,
        Guid userId,
        string title,
        DateOnly todoDate,
        string? notes,
        TodoPriority priority,
        DateTimeOffset createdAt) =>
        new(id, userId, title, todoDate, notes, priority, null, createdAt);

    /// <summary>Creates a new todo that was auto-generated by a <see cref="DailyRoutine"/>.</summary>
    public static PersonalTodo CreateFromDailyRoutine(
        Guid id,
        Guid userId,
        Guid dailyRoutineId,
        string title,
        DateOnly todoDate,
        string? notes,
        TodoPriority priority,
        DateTimeOffset createdAt) =>
        new(
            id,
            userId,
            title,
            todoDate,
            notes,
            priority,
            dailyRoutineId,
            createdAt);

    /// <summary>
    /// Updates the todo's editable fields. If the new date is moved back to (or before)
    /// its original date, any prior carry-over marker is cleared since the todo is no
    /// longer "late" relative to where it started.
    /// </summary>
    public void Update(
        string title,
        DateOnly todoDate,
        string? notes,
        TodoPriority priority,
        DateTimeOffset updatedAt)
    {
        Title = NormalizeTitle(title);
        TodoDate = todoDate;
        if (todoDate <= OriginalTodoDate)
        {
            CarriedOverFromDate = null;
        }

        Notes = NormalizeNotes(notes);
        Priority = priority;
        UpdatedAt = updatedAt;
    }

    /// <summary>
    /// Rolls an unfinished todo forward to a later date (e.g. an end-of-day sweep of
    /// incomplete items). No-op if already completed or if the target date is not
    /// actually later. Records the original date the first time this happens so
    /// <see cref="IsCarriedOver"/> reflects the todo's true origin even after multiple carries.
    /// </summary>
    public void CarryOverTo(DateOnly nextDate, DateTimeOffset carriedAt)
    {
        if (IsCompleted || nextDate <= TodoDate)
        {
            return;
        }

        CarriedOverFromDate ??= TodoDate;
        TodoDate = nextDate;
        UpdatedAt = carriedAt;
    }

    /// <summary>Marks the todo completed. Idempotent — no-op if already completed.</summary>
    public void Complete(DateTimeOffset completedAt)
    {
        if (IsCompleted)
        {
            return;
        }

        IsCompleted = true;
        CompletedAt = completedAt;
        UpdatedAt = completedAt;
    }

    /// <summary>Reopens a completed todo. Idempotent — no-op if not currently completed.</summary>
    public void Reopen(DateTimeOffset reopenedAt)
    {
        if (!IsCompleted)
        {
            return;
        }

        IsCompleted = false;
        CompletedAt = null;
        UpdatedAt = reopenedAt;
    }

    /// <summary>Adds a comment to the todo.</summary>
    public PersonalTodoComment AddComment(
        Guid commentId,
        string body,
        DateTimeOffset createdAt)
    {
        var comment = new PersonalTodoComment(commentId, Id, body, createdAt);
        _comments.Add(comment);
        return comment;
    }

    // Trims the title and enforces it is present and within the 160-character limit.
    private static string NormalizeTitle(string title)
    {
        var normalized = title.Trim();
        if (string.IsNullOrWhiteSpace(normalized))
        {
            throw new DomainValidationException(
                "Todo title is required.");
        }

        if (normalized.Length > 160)
        {
            throw new DomainValidationException(
                "Todo title must be 160 characters or fewer.");
        }

        return normalized;
    }

    // Trims notes (blank becomes null) and enforces the 1000-character limit.
    // Internal so DailyRoutine can reuse the same normalization for its own notes field.
    internal static string? NormalizeNotes(string? notes)
    {
        if (string.IsNullOrWhiteSpace(notes))
        {
            return null;
        }

        var normalized = notes.Trim();
        if (normalized.Length > 1000)
        {
            throw new DomainValidationException(
                "Todo notes must be 1000 characters or fewer.");
        }

        return normalized;
    }
}
